todo_project/login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'


urlpatterns = [
        path('login/', views.login, name='login'),
        path('logout/', views.logout, name='logout'),
        path('password_reset/', views.password_reset, name='password_reset'),
        path('password_reset_secret/<str:secret>/', views.password_reset_secret, name='password_reset_secret'),
        path('password_reset_form/', views.password_reset_form, name='password_reset_form'),
        path('sign_up/', views.sign_up, name='sign_up'),
        path('delete_account/', views.delete_account, name='delete_account'),
]

todo_project/todo_app/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = "todo_app"

urlpatterns = [
   path('', views.index, name='index'),
   path('completed_todos/', views.completed_todos, name='completed_todos'),
   path('update_status/', views.update_status, name='update_status'),
   path('delete_todo/', views.delete_todo, name='delete_todo'),
   
]

todo_project/todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_app.urls')),
    path('accounts/', include('login_app.urls')),
]

todo_project/login_app/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe


class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    secret = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'{self.user} - {self.created_timestamp}'

todo_project/todo_app/models.py
from django.contrib.auth.models import User
from django.db import models


class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=250)
    status = models.BooleanField(default=False)

    @classmethod
    def create(cls, user, text):
        todo = cls()
        todo.user = user
        todo.text = text
        todo.save() 
     
    
    def toggle_status(self):
        self.status = self.status
        self.save()


    def __str__(self):
        return f"{self.text}  {self.status}"

todo_project/login_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from . import models


def login(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('todo_app:index'))
        else:
            context = {'error': 'Bad username or password.'}
    return render(request, 'login_app/login.html', context)


def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('login_app:login'))


def password_reset(request):
    context = {}

    if request.method == "POST":
        email = request.POST['email']
        user = User.objects.get(email=email)
        reset_request = models.PasswordResetRequest()
        reset_request.user = user
        reset_request.save()
        url = reverse('login_app:password_reset_secret', args=[f'{reset_request.secret}'])
        url = f'{request.scheme}://{request.META["HTTP_HOST"]}{url}'
        print(url)
        context = {'message': 'Please click the link in the email we sent to you.'}

    return render(request, 'login_app/password_reset.html', context)


def password_reset_secret(request, secret):
    context = {'secret': secret}
    return render(request, 'login_app/password_reset_form.html', context)


def password_reset_form(request):
    email = request.POST['email']
    password = request.POST['password']
    confirm_password = request.POST['confirm_password']
    secret = request.POST['secret']

    user = User.objects.get(email=email)
    reset_request = models.PasswordResetRequest.objects.get(user=user,secret=secret)
    if password == confirm_password:
        user.set_password(password)
        user.save()
        reset_request.save()
        return HttpResponseRedirect(reverse('login_app:login'))
    context = {'error': 'Something went wrong, try again, don\'t screw up this time!'}
    return render(request, 'login_app/password_reset_form.html', context)


def sign_up(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        email = request.POST['email']
        if password == confirm_password:
            if User.objects.create_user(username, email, password):
                return HttpResponseRedirect(reverse('login_app:login'))
            else:
                context = {'error': 'Could not create user - try somethig else.'}
        else:
            context = {'error': 'Passwords do not match.'}
    return render(request, 'login_app/sign_up.html', context)


def delete_account(request):
    pass

todo_project/todo_app/views.py
from django.shortcuts import render, get_object_or_404, reverse
from .models import Todo
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    if request.method == 'POST':
        Todo.create(request.user, request.POST['text'])

    todos = Todo.objects.filter(status=False).filter(user=request.user)
    context = {
        'todos': todos,
    }
    return  render(request, 'todo_app/index.html', context)

@login_required
def completed_todos(request):
    todos = Todo.objects.filter(status=True).filter(user=request.user)
    context = {
            'todos': todos,
    }
    return render(request, 'todo_app/completed_todos.html', context)

@login_required
def update_status(request):
    pk = request.POST['pk']
    todo = get_object_or_404(Todo, pk=pk)
    todo.toggle_status()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

@login_required
def delete_todo(request):
    pk = request.POST['pk']
    todo = get_object_or_404(Todo, pk=pk)
    todo.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

todo_project/login_app/templates/login_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <a href="{% url 'login_app:sign_up' %}">Sign Up</a>
    <a href="{% url 'login_app:password_reset' %}">Reset Password</a>
    <hr>
    <form action="{% url 'login_app:login' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <br />
        <input type="password" name="password" placeholder="Password">
        <br />
        <input type="submit" value="Login">
    </form>
    <hr>
    {% if error %}<p style="color:red;">{{ error }}</p>{% endif %}
</body>
</html>

todo_project/login_app/templates/login_app/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset</title>
</head>
<body>
    <h1>Password Reset</h1>
    <a href="{% url 'login_app:login' %}">Log In</a>
    <hr />
    <form action="{% url 'login_app:password_reset' %}" method="POST">
        {% csrf_token %}
        <input type="email" name="email" placeholder="email">
        <input type="submit" value="Reset Password">
    </form>
    <hr />
    {% if message %}{{ message }}{% endif %}
</body>
</html>

todo_project/login_app/templates/login_app/password_reset_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Please Set New Password</title>
</head>
<body>
    <h1>New Password</h1>
    <hr />
    <form action="{% url 'login_app:password_reset_form' %}" method="POST">
        {% csrf_token %}
        <input type="email" name="email" placeholder="Email Address">
        <input type="password" name="password" placeholder="Password">
        <input type="password" name="confirm_password" placeholder="Confirm Password">
        <input type="hidden" name="secret" value="{{ secret }}">
        <input type="submit" value="Set New Password">
    </form>
    <hr />
    {% if error %}{{ error }}{% endif %}
</body>
</html>

todo_project/login_app/templates/login_app/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
    <h1>Sign Up</h1>
    <a href="{% url 'login_app:login' %}">Log In</a>
    <hr>
    <form action="{% url 'login_app:sign_up' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="User Name">
        <input type="password" name="password" placeholder="Password">
        <input type="password" name="confirm_password" placeholder="Confirm Password">
        <input type="email" name="email" placeholder="Email Address">
        <input type="submit" value="Sign Up">
    </form>
</body>
</html>

todo_project/todo_app/templates/todo_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'todo_app/styles.css' %}" media="screen"/>
    
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

    <h1>Todos</h1>
    Hello, {{ user.username }}.
    <a href="{% url 'login_app:logout' %}">Log Out</a>
    <br />
    <a href="{% url 'todo_app:completed_todos' %}">Completed Todos</a>
    
    {% block content %}
    {% endblock %}
    {% block footer %}
    {% endblock %}

</body>
</html>

todo_project/todo_app/templates/todo_app/completed_todos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Completed Todos</title>
</head>
<body>

    {% extends "todo_app/base.html" %}
    {% block title %} Completed Todos  {% endblock %}

    {% block content %}



    <h1>Completed Todos</h1>
    <a href="{% url 'todo_app:index' %}">Home</a>
    <hr />
    <ul>
    {% for todo in todos %}
        <li>
            <form action="{% url 'todo_app:update_status' %}" method="POST">
                {% csrf_token %}
                <input type="checkbox" name="status" {% if todo.status  %}checked{% endif %}>
                <input type="submit" value="Update">
                {{ todo.text }}
                <input type="hidden" name="pk" value="{{todo.pk}}">
            </form>
        </li>
    {% endfor %}
    </ul>
    <hr />
    {% endblock %}
</body>
</html>

todo_project/todo_app/templates/todo_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todos</title>
</head>
<body>
    {% extends "todo_app/base.html" %}


    {% block content %}

    <hr />
    <ul>
    {% for todo in todos %}
        <li>
            <form action="{% url 'todo_app:update_status' %}" method="POST">
                {% csrf_token %}
                <input type="checkbox" name="status" {% if todo.status  %}checked{% endif %}>
                <input type="submit" value="Update">
                <button formaction="{% url 'todo_app:delete_todo' %}">Delete</button>
                {{ todo.text }}
                <input type="hidden" name="pk" value="{{todo.pk}}">
            </form>
        </li>
    {% endfor %}
    </ul>
    <hr />
    <form action="." method="POST">
        {% csrf_token %}
        <input type="text" placeholder="what to do ..." name="text">
        <input type="submit" value="OK">
    </form>
  
    {% endblock %}
</body>
</html>